# https://alacritty.org/config-alacritty.html

import = [
  "~/.config/alacritty/catppuccin-frappe.toml",
  "~/.config/alacritty/keybindings.toml",
]

[window]

padding = { x = 20, y = 20 }

opacity = 0.9

[font]

normal = { family = "RecMonoSmCasual Nerd Font Mono", style = "Regular" }

size = 14

[selection]

save_to_clipboard = true

[mouse]

hide_when_typing = true
