preview = true
line-length = 88

[lint]
select = ["E", "W", "F", "I"]

[lint.isort]
case-sensitive = true
force-to-top = ["typing"]
force-sort-within-sections = true

[format]
quote-style = "preserve"
